# 1. Bag of Words

In [1]:
import numpy as np
import pandas as pd

C:\Users\hp\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [5]:
df = pd.DataFrame({'text': ['people watch ipl', 'ipl watch ipl', 'people write comment', 'ipl write comment'], 
                   'output': [1, 1, 0, 0]})

In [6]:
df

text  output
0      people watch ipl       1
1         ipl watch ipl       1
2  people write comment       0
3     ipl write comment       0

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [10]:
bow = cv.fit_transform(df['text'])

In [11]:
# vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'ipl': 1, 'write': 4, 'comment': 0}


In [13]:
# converting first sentences into vector
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 1 0]]
[[0 2 0 1 0]]


In [16]:
#$ lets take a new sentence for prediction
cv.transform(['ipl watch and write comment of ipl']).toarray()
# out of vocabluary is handled  automaticallyhere 'and'

array([[1, 2, 0, 1, 1]], dtype=int64)

# 2. n- grams

In [17]:
df = pd.DataFrame({'text': ['people watch ipl', 'ipl watch ipl', 'people write comment', 'ipl write comment'], 
                   'output': [1, 1, 0, 0]})

In [18]:
df

text  output
0      people watch ipl       1
1         ipl watch ipl       1
2  people write comment       0
3     ipl write comment       0

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2)) # for bigram

In [21]:
bow = cv.fit_transform(df['text'])

In [22]:
# vocab
print(cv.vocabulary_)

{'people watch': 2, 'watch ipl': 4, 'ipl watch': 0, 'people write': 3, 'write comment': 5, 'ipl write': 1}


In [23]:
# converting first sentences into vector
print(bow[0].toarray())
print(bow[1].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]


In [24]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3)) # for bigram

In [25]:
bow = cv.fit_transform(df['text'])

In [26]:
# vocab
print(cv.vocabulary_)

{'people watch ipl': 2, 'ipl watch ipl': 0, 'people write comment': 3, 'ipl write comment': 1}


# 3. TF-IDF 

In [23]:
df = pd.DataFrame({'text': ['people watch ipl', 'ipl watch ipl', 'people write comment', 'ipl write comment'], 
                   'output': [1, 1, 0, 0]})

In [24]:
df

text  output
0      people watch ipl       1
1         ipl watch ipl       1
2  people write comment       0
3     ipl write comment       0

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

# Sample DataFrame
df = pd.DataFrame({'text': ['people watch ipl', 'ipl watch ipl', 'people write comment', 'ipl write comment'], 
                   'output': [1, 1, 0, 0]})

# Initialize TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()

# Fit the vectorizer to the text data and transform it to TF-IDF representation
tfidf_matrix = tfidf_vectorizer.fit_transform(df['text'])

# Convert the TF-IDF matrix to a dense array
tfidf_array = tfidf_matrix.toarray()

# Display the TF-IDF array
print(tfidf_array)


[[0.         0.49681612 0.61366674 0.61366674 0.        ]
 [0.         0.8508161  0.         0.52546357 0.        ]
 [0.57735027 0.         0.57735027 0.         0.57735027]
 [0.61366674 0.49681612 0.         0.         0.61366674]]


In [31]:
# Print IDF values
print("IDF values:", tfidf_vectorizer.idf_)

# Print feature names
print("Feature names:", tfidf_vectorizer.get_feature_names_out())

IDF values: [1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]
Feature names: ['comment' 'ipl' 'people' 'watch' 'write']
